default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= Rails.application.credentials.db_name %>
  host: <%= Rails.application.credentials.db_host %>
  username: <%= Rails.application.credentials.db_username %>
  password: <%= Rails.application.credentials.db_password %>

test:
  <<: *default
  database: <%= Rails.application.credentials.db_name %>
  host: <%= Rails.application.credentials.db_host %>
  username: <%= Rails.application.credentials.db_username %>
  password: <%= Rails.application.credentials.db_password %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
